### ISSUE TITLE
[kube-prometheus-stack]  data: Too long: must have at most 1048576 bytes

### ISSUE THREAD

**Issue by my1990** [prometheus-community/helm-charts#3345] opened 2023-05-08 02:16 UTC
### Describe the bug a clear and concise description of what the bug is.

When updating the kube prometheus stack, an error message is reported indicating that the secret is too large。
I would like to ask why ”secret/sh. help. release. v1. kube prometheus stack. v1“ is so large, and if it is reduced, it ensures that I can update smoothly

### What's your helm version?

v3.2.0

### What's your kubectl version?

v1.21.5

### Which chart?

kube-prometheus-stack-28.0.1-hc.1

### What's the chart version?

0.53.1

### What happened?

The secret is too large to upgrade

### What you expected to happen?

update success

### How to reproduce it?

Helm install is normal, but cannot be upgrade

### Enter the changed values of values.yaml?

alertmanager:
  oamwebhookip: 10.10.103.187
  ## Deploy alertmanager
  ##
  enabled: true
  dingtalk:
    enabled: false
  ## Annotations for Alertmanager
  ##
  annotations: {}

  ## Api that prometheus will use to communicate with alertmanager. Possible values are v1, v2
  ##
  apiVersion: v2

  ## Service account for Alertmanager to use.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  ##
  serviceAccount:
    create: true
    name: ""
    annotations: {}

  ## Configure pod disruption budgets for Alertmanager
  ## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
  ## This configuration is immutable once created and will require the PDB to be deleted to be changed
  ## https://github.com/kubernetes/kubernetes/issues/45398
  ##
  podDisruptionBudget:
    enabled: false
    minAvailable: 1
    maxUnavailable: ""

  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  ##
  config:
    global:
      resolve_timeout: "5m"
      smtp_smarthost: "smtp.exmail.qq.com:465"
      smtp_from: "mail@harmonycloud.cn"
      smtp_auth_username: "609755396@qq.com"
      smtp_auth_password: ""
      smtp_hello: "altermanager"
      smtp_require_tls: false
    inhibit_rules:
    - equal:
      - namespace
      - alertname
      source_match:
        severity: "critical"
      target_match_re:
        severity: "warning|info"
    - equal:
      - namespace
      - alertname
      source_match:
        severity: "warning"
      target_match_re:
        severity: "info"
    receivers:
    - name: "Default"
    - name: "Watchdog"
    - name: "oamwebhook"
      webhook_configs:
      - url: "http://{{ .Values.alertmanager.oamwebhookip }}/alertmanager/webhook"
    - name: DingTalkWebhook
      webhook_configs:
      - url: "http://alertmanager-webhook-dingtalk/dingtalk/webhook/send"
        send_resolved: true
    - name: Email
      email_configs:
      - to: "zhangpan@harmonycloud.cn"
        send_resolved: true
    route:
      group_interval: "5m"
      group_wait: "30s"
      receiver: "webhook"
      repeat_interval: "12h"
      routes:
      - match:
          severity: "critical"
        receiver: "Critical"
        group_by: ['alertname', 'service', 'clusterId']
      - match:
          platform": "true"
        group_by: ["prometheusRuleName"]
        receiver: "oamwebhook"
      - receiver: Email
        match_re:
          serverity : email
        group_wait: 10s
      - receiver: DingTalkWebhook
        match:
          alert: "true"
    templates:
    - /etc/alertmanager/config/*.tmpl

### Enter the command that you execute and failing/misfunctioning.

helm upgrade kube-prometheus-stack -n monitoring --values kube-prometheus-stack/values.yaml kube-prometheus-stack/

### Anything else we need to know?

none

**Comment by QuentinBisson** [comment] 2023-05-23 20:26
@my1990 can you try your values file with the latest release? The size will have to be addressed soon

**Comment by kodispace** [comment] 2023-05-24 17:23
@QuentinBisson Below is the error with the latest one
```
kube-prometheus-stack % helm install kube-prometheus-stack . --namespace observability  
Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.kube-prometheus-stack.v1" is invalid: data: Too long: must have at most 1048576 bytes
```

**Comment by kodispace** [comment] 2023-05-24 17:38
Tried Via ArgoCD 
one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "prometheusagents.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes,CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes. Retrying attempt #5 at 5:36PM.

**Comment by javad2157** [comment] 2023-06-03 08:00
I have the same problem. I try to install prometheus-stack with argocd and i got this error
![image](https://github.com/prometheus-community/helm-charts/assets/89399278/244d3551-d7b4-4910-9f4f-e7055ee1e66d)

**Comment by xiu** [comment] 2023-06-03 12:56
Using ArgoCD, you need to enable `serverSideApply` in the Application resource (see https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply) for the CRDs to be applied properly.

**Comment by gogo199432** [comment] 2023-06-03 14:18
Tried this but didn't seem to do anything, still getting the same error. Also tried adding it as an annotation, same result.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 46.6.0
    chart: kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

**Comment by janosmiko** [comment] 2023-06-10 15:21
The problem lies in the `last-applied-configuration` annotation.

Try to delete the previous ArgoCD application manually or add `Replace=true` to the the `syncPolicy.syncOptions` like this:
```yaml
...
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - ServerSideApply=true
```

**Comment by Roman-Simik** [comment] 2023-06-10 18:33
> Using ArgoCD, you need to enable `ServerSideApply` in the Application resource (see https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply) for the CRDs to be applied properly.

I can confirm this solved the issue for me, thanks!

**Comment by konglingning** [comment] 2023-06-29 06:22
Hi, I encounter the same error when deploying the latest version:
`helm install kube-prometheus-stack . --namespace monitoring -f values.yaml
Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.kube-prometheus-stack.v1" is invalid: data: Too long: must have at most 1048576 bytes`

**Comment by djonko** [comment] 2023-07-04 02:38
> helm install -n monitoring prometheus prometheus-community/kube-prometheus-stack -f values.yaml
Error: INSTALLATION FAILED: create: failed to create: Secret "sh.helm.release.v1.prometheus.v1" is invalid: data: Too long: must have at most 1048576 bytes

same error

**Comment by jkroepke** [comment] 2023-07-04 05:00
Duplicate of #3544

**Closed** 2023-07-04 05:02 UTC
Labels: bug

**Comment by bellaned** [comment] 2023-07-04 07:43
> Tried Via ArgoCD
> one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "prometheusagents.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes,CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes.

Same issue. Tried with: 
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/sync-options: ServerSideApply=true
but it doesn't fix the problem.

**Comment by djonko** [comment] 2023-07-04 16:24
> Duplicate of #3544

I switch to version 47.1.0 and it works . thanks

`helm install -n monitoring prometheus prometheus-community/kube-prometheus-stack --version 47.1.0  -f values.yaml`

**Comment by aeldakhli** [comment] 2023-08-19 23:04
I'm using version 48.2.2. I followed the solution provided by @xiu and issue is fixed. Thanks @xiu 
`apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps
  namespace: argocd
spec:
  syncPolicy:
   syncOptions:
    - ServerSideApply=true`

**Comment by DanPhonovation** [comment] 2023-09-29 19:37
I'm using devtron (which uses ArgoCD under the hood) and getting this same error. But I have no apiVersion: argoproj.io to modify for ServerSideApply

**Comment by huziahmetovsv** [comment] 2023-11-20 11:41
Same error. Added
```
spec:
  syncPolicy:
   syncOptions:
    - ServerSideApply=true
 ```
and then manually synchronize failed objects from argocd interface with "replace" checkbox. Works for me

**Comment by spoletum** [comment] 2024-03-10 19:17
> Same error. Added
> 
> ```
> spec:
>   syncPolicy:
>    syncOptions:
>     - ServerSideApply=true
> ```
> 
> and then manually synchronize failed objects from argocd interface with "replace" checkbox. Works for me

Worked like a treat for a similar issue, Camel-K deployed using ArgoCD. Thanks!

**Comment by ccpatrut** [comment] 2024-06-22 18:05
It seems to be that even getting the CRD with currl and apply it after generate the error, regardless if we use Argocd or not:
For instance: 
```
curl -O https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml

kubectl apply -f monitoring.coreos.com_thanosrulers.yaml

```

Is generating this warning:
![image](https://github.com/prometheus-community/helm-charts/assets/44428503/84712653-dceb-4f6c-bf2f-9e150055e4e3)

![image](https://github.com/prometheus-community/helm-charts/assets/44428503/5d5bcdac-494e-4f66-b7f4-b7f2d82b7ff4)

**Comment by dongjiang1989** [comment] 2024-11-14 03:17
@ccpatrut  Please check https://prometheus-operator.dev/docs/platform/troubleshooting/#customresourcedefinition--is-invalid-metadataannotations-too-long-issue :)

**Comment by enoliveira** [comment] 2025-02-25 23:05
I tried the above. But, only adding the annotation worked for me.

`apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
    argocd.argoproj.io/sync-options: ServerSideApply=true`
