### ISSUE TITLE
[kube-prometheus-stack] Graph going blank

### ISSUE THREAD

**Issue by sojugeorge** [prometheus-community/helm-charts#4361] opened 2024-03-15 12:39 UTC
### Describe the bug a clear and concise description of what the bug is.

Graph going blank

### What's your helm version?

[ec2-user@f3bbba6824da aws]$ helm version WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ec2-user/.kube/config WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ec2-user/.kube/config version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"} [ec2-user@f3bbba6824da aws]$

### What's your kubectl version?

[ec2-user@f3bbba6824da aws]$ kubectl version Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.7-eks-b9c9ed7", GitCommit:"217b17b5aed5ddc370672ff6c12d78037cbb8e7a", GitTreeState:"clean", BuildDate:"2024-03-02T03:47:14Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.21) and server (1.28) exceeds the supported minor version skew of +/-1 [ec2-user@f3bbba6824da aws]$

### Which chart?

https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

### What's the chart version?

v0.71.2

### What happened?

Iam gettingissues on grafana dashboard saying my graph plugin is depicated as it was using angular. 

how to fir this issue

### How to reproduce it?

attached screenshots
![Screenshot 2024-03-15 at 6 03 14 PM](https://github.com/prometheus-community/helm-charts/assets/118244107/c4446356-714b-4cb5-9b8b-41d9beb21669)

### Enter the command that you execute and failing/misfunctioning.

helm install monitoring kube-prometheus-stack -n monitoring

as chart version was fixed like v0.71.2

**Comment by imroc** [comment] 2024-04-03 03:01
+1

**Comment by sojjan1337** [comment] 2024-04-12 09:14
+1

**Comment by jkroepke** [comment] 2024-04-14 16:20
> saying my graph plugin is depicated as it was using angular.

duplicate of https://github.com/prometheus-community/helm-charts/issues/4380 - follow the conversation there.

**Closed by jkroepke** 2024-04-14 16:20 UTC
Labels: bug
