### ISSUE TITLE
[kube-prometheus-stack] Prometheus doesn't respect ServiceMonitor created by kube-state-metrics chart

### ISSUE THREAD

**Issue by skarj** [prometheus-community/helm-charts#1631] opened 2021-12-23 15:05 UTC
### Describe the bug a clear and concise description of what the bug is.

Prometheus doesn't respect ServiceMonitor created by `kube-state-metrics` Helm chart by default

### What's your helm version?

3.7.0

### What's your kubectl version?

1.23.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

25.1.0

### What happened?

`kube-prometheus-stack` Helm chart creates `Prometheus` with 

```
  serviceMonitorSelector:
    matchLabels:
      release: prometheus-operator
```

`kube-state-metrics` Helm chart creates `ServiceMonitor` without a label `release: prometheus-operator`

so the `kube-state-metrics`  target doesn't appear in the Prometheus

### What you expected to happen?

`kube-prometheus-stack` default configuration should have working `kube-state-metrics` out of the box

### Enter the command that you execute and failing/misfunctioning.

applying using terraform

### Anything else we need to know?

Workarounds are:

```
kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator
```
or

`prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false`

**Comment by lud97x** [comment] 2021-12-29 14:41
+1 I can reproduce this issue with the chart version v25.1.0

**Comment by monotek** [comment] 2021-12-29 15:17
Not sure how a fix should look like as we don't know whats the releasename the user chooses for kube-prometheus-stack.

**Comment by groundhog2k** [comment] 2022-01-04 14:05
Possibly using another label makes it more independent from the release name used for helm:
```
kube-state-metrics:
  prometheus:
    monitor:
      additionalLabels:
        app: kube-prometheus-stack-operator
```

**Comment by devent** [comment] 2022-01-04 14:35
Can you at least document this in the docu? Here: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

**Comment by monotek** [comment] 2022-01-04 15:42
I guess adding the release label to kube-state-metrics would be easiest solution.
@mrueg 
thoughts?

**Comment by lud97x** [comment] 2022-01-04 16:19
Hi, if it helps, we share the same helm release's name for our prometheus and kube state metric instance. So adding the label `release` might quickly solve the issue here https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/_helpers.tpl#L59
```
release: {{ $.Release.Name | quote }}
```

**Comment by joeldeteves** [comment] 2022-01-04 18:30
> Workarounds are:
> 
> ```
> kube-state-metrics:
>   prometheus:
>     monitor:
>       enabled: true
>       additionalLabels:
>         release: prometheus-operator
> ```
> 
> or
> 
> `prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false`

The fix for me was to set `release` to **kube-prometheus-stack**:

```
kube-state-metrics:
  prometheus:
    monitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
```

Thank you,

**Comment by mrueg** [comment] 2022-01-04 21:55
@monotek the solution @joeldeteves provided sounds like a good one. @joeldeteves do you want to create a PR for that and add it to kube-prometheus-stack?

**Comment by joeldeteves** [comment] 2022-01-04 22:00
> @monotek the solution @joeldeteves provided sounds like a good one. @joeldeteves do you want to create a PR for that and add it to kube-prometheus-stack?

Not my area of expertise. I just did what @skarj suggested except mine turned out to be labelled differently.

If you want to try it yourself simply create a `values.yaml` with these values (or add to your existing one) and apply using `helm upgrade -f`

Here's the full command for our use case:

```helm upgrade -f values.yaml kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring```

Afterwards I re-created the kube-state-metrics pod and it started working.

**Comment by monotek** [comment] 2022-01-04 23:49
> @monotek the solution @joeldeteves provided sounds like a good one. @joeldeteves do you want to create a PR for that and add it to kube-prometheus-stack?

I think we can't set a fixed release label in kube-prometheus-stack as we would need to know the name of the release it is installed with.

That's the reason I thinks it's easier to add the release label via templating in kube-state-metrics so it can use the actual used release name if Kube-prometheus-stack.

**Comment by wu105** [comment] 2022-01-05 22:36
as of kube-prometheus-stack-27.0.1, all the release labels seems "prometheus" thus the workaround may not be applicable.

**Comment by mrueg** [comment] 2022-01-05 22:44
> > @monotek the solution @joeldeteves provided sounds like a good one. @joeldeteves do you want to create a PR for that and add it to kube-prometheus-stack?
> 
> I think we can't set a fixed release label in kube-prometheus-stack values file as we would need to know the name of the release it is installed with.
> 
> That's the reason I thinks it's easier to add the release label via templating in kube-state-metrics so it can use the actual used release name in Kube-prometheus-stack.

Ah thanks for clarifying! I'd suggest to add it to https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/_helpers.tpl#L59 and make it conditional maybe via a value like "externalReleaseLabel" that can be set to true?

**Comment by dotdc** [comment] 2022-01-05 23:27
Was thinking about this issue and here's my thoughts:

If we want to keep `kube-prometheus-stack` default behavior of using a label for ServiceMonitors, maybe we should consider using another one. The `release` label will always bring confusion and even be a problem when dealing with subcharts.

Back in the `prometheus-operator` days, I remember using `prometheus.io/scrape: "true"` for this purpose, maybe this one could do the trick? Or maybe we can create a brand new set of labels?

I was also wondering why `kube-state-metrics` ServiceMonitor was removed from `kube-prometheus-stack` between 23.x to 24.x and found the PR : https://github.com/prometheus-community/helm-charts/issues/1425 

We could also re-consider this initial change. Isn't it easier to manage ServiceMonitors based on the deployment context?
(this implies having to maintain one in both chart) 

Anyone have thoughts on this?

**Comment by monotek** [comment] 2022-01-06 00:18
> > > @monotek the solution @joeldeteves provided sounds like a good one. @joeldeteves do you want to create a PR for that and add it to kube-prometheus-stack?
> > 
> > 
> > I think we can't set a fixed release label in kube-prometheus-stack values file as we would need to know the name of the release it is installed with.
> > That's the reason I thinks it's easier to add the release label via templating in kube-state-metrics so it can use the actual used release name in Kube-prometheus-stack.
> 
> Ah thanks for clarifying! I'd suggest to add it to https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/_helpers.tpl#L59 and make it conditional maybe via a value like "externalReleaseLabel" that can be set to true?

Yes, that was my idea too. Just had not time to create the pr. Will do tomorrow :)

**Comment by monotek** [comment] 2022-01-06 14:16
Create the PR: https://github.com/prometheus-community/helm-charts/pull/1683 :)

**Comment by monotek** [comment] 2022-01-07 17:15
Pr which uses it in kube-prometheus-stack: https://github.com/prometheus-community/helm-charts/pull/1692

**Comment by dotdc** [comment] 2022-01-18 18:59
both PR are merged, can I close this?

**Closed** 2022-01-18 20:08 UTC
Labels: bug
