### ISSUE TITLE
[kube-prometheus-stack] Reference of invalid Prometheus rules in Grafana 1.14 rsrc USE dashboard

### ISSUE THREAD

**Issue by jaanhio** [prometheus-community/helm-charts#1067] opened 2021-06-11 15:31 UTC
**Describe the bug**
This was already reported in https://github.com/prometheus-community/helm-charts/issues/1054 but i have no idea why issue was closed before the fixes are verified. Creating this issue again so that it does not go unfixed........
Below are just copy-pasted from  https://github.com/prometheus-community/helm-charts/issues/1054 

Noticed 2 of the default Grafana USE Method Node/Cluster dashboards are referencing Prometheus rules that does not exist, which resulted in "No data" displayed on the affected panels.

<img width="1595" alt="Screenshot 2021-06-09 at 5 08 43 PM" src="https://user-images.githubusercontent.com/6738954/121328286-c7af9a00-c946-11eb-976f-51100d1031c5.png">
<img width="1604" alt="Screenshot 2021-06-09 at 5 19 33 PM" src="https://user-images.githubusercontent.com/6738954/121328604-0b0a0880-c947-11eb-884d-95978c1d1e4f.png">

**Managed to trace the changes back to a particular release and PR.**

Release v15.4.6: https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-15.4.6...main
PR: https://github.com/prometheus-community/helm-charts/pull/951/files

Prometheus rules file: https://github.com/prometheus-community/helm-charts/blob/217a72df8d80e430e7465656a[…]-stack/templates/prometheus/rules-1.14/node-exporter.rules.yaml

i am not entirely clear what is the purpose for the change but if its unintended, i can make a PR to revert this.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
16.5.0 (it should affect all versions >= v15.4.6)

**What happened**:
Grafana 1.14-dashboards USE Node/Cluster are showing "No data" for some of the panels. Root cause is due to the affected panels referencing Prometheus rules that do not exist.

**What you expected to happen**:
The affected panels should pull data from Prometheus rules specified here (https://github.com/prometheus-community/helm-charts/blob/217a72df8d80e430e7465656a[…]-stack/templates/prometheus/rules-1.14/node-exporter.rules.yaml) and display accordingly.

**How to reproduce it** (as minimally and precisely as possible):
Use kube-prometheus-stack >= v15.4.6

**Changed values of values.yaml** (only put values which differ from the defaults):
No custom `values.yaml` used.

**The helm command that you execute and failing/misfunctioning**:
```console
helm install my-release prometheus-community/kube-prometheus-stack
```

**Anything else we need to know**:

**Comment by mrueg** [comment] 2021-06-11 16:43
The dashboards and rules are synced from the upstream project: https://github.com/prometheus-operator/kube-prometheus

Change was made in:
https://github.com/prometheus-operator/kube-prometheus
/commit/28d58a9dbc0140ea6d5cc2b1d655912071e1051f#diff-ad9b0e030d012e83adcdb45dc042bd9364922e140e0c93f247796732a5676e69

**Comment by mrueg** [comment] 2021-06-12 11:08
Duplicate of https://github.com/prometheus-community/helm-charts/issues/1054 Let's keep the conversation in a single issue please.

**Closed by mrueg** 2021-06-12 11:08 UTC
Labels: bug
