### ISSUE TITLE
[kube-prometheus-stack] Grafana Dashboards Giving Warning for AngularJS Deprecation

### ISSUE THREAD

**Issue by RishabhKumarGupta** [prometheus-community/helm-charts#4393] opened 2024-03-26 11:48 UTC
### Describe the bug a clear and concise description of what the bug is.

All the grafana dashboards giving the warning related to AngularJS Depreication . The use of AngularJS in Grafana has been [deprecated](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/) in favor of React. Support for AngularJS will be turned off by default in Grafana 11 . 

<img width="198" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/35447048/ee81684b-9e1b-4f25-b157-abd282d74bc9">

### What's your helm version?

version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"windows/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.11", GitCommit:"3cd242c51317aed8858119529ccab22079f523b1", GitTreeState:"clean", BuildDate:"2023-11-15T16:50:12Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

57.1.0

### What happened?

Grafana will be stopped supporting the dashboards that are using AngularJS Plugins in Grafana 11 .

### What you expected to happen?

Grafana Dashboards Needs to migrate from AngularJS to React Based Plugins , for more info https://grafana.com/docs/grafana/latest/developers/angular_deprecation/angular-plugins/#automatic-migration-of-plugins

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --values myvalues.yaml --namespace prometheus --version=57.1.0

### Anything else we need to know?

When we are planning to do this change ?

**Comment by jkroepke** [comment] 2024-03-26 12:01
duplicate of https://github.com/prometheus-community/helm-charts/issues/4380

**Closed by jkroepke** 2024-03-26 12:01 UTC
Labels: bug
