### ISSUE TITLE
[name of the chart e.g. prometheus-kube-stack] Issue Title

### ISSUE THREAD

**Issue by abyssmemes** [prometheus-community/helm-charts#1939] opened 2022-03-31 10:28 UTC
### Describe the bug a clear and concise description of what the bug is.

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

latest

### Enter the command that you execute and failing/misfunctioning.

helm install grafana  -f grafana.yaml prometheus-community/kube-prometheus-stack

**Comment by monotek** [comment] 2022-03-31 11:41
duplicate of: https://github.com/prometheus-community/helm-charts/issues/1923

**Closed by monotek** 2022-03-31 11:41 UTC
Labels: bug
