### ISSUE TITLE
[kube-prometheus-stack] Recent prometheuses.monitoring.coreos.com changes don't allow to re-deploy CRD 

### ISSUE THREAD

**Issue by alen-z** [prometheus-community/helm-charts#2317] opened 2022-07-28 14:23 UTC
### Describe the bug a clear and concise description of what the bug is.

Recent `prometheuses.monitoring.coreos.com` changes don't allow to re-deploy CRD since annotation referencing older version is to big.

### What's your helm version?

3.9.2

### What's your kubectl version?

1.24.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

38.0.2

### What happened?

Applying latest CRDs is failing on second apply since last version annotation is trying to be applied.

```
one or more objects failed to apply, reason: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

### What you expected to happen?

CRD can be applied without too big annotation issue.

### Enter the command that you execute and failing/misfunctioning.

We use Argo for testing. Replacing resource works for the first time, but second sync fails (apply) because annotation of last CRD version is too big. Only way to maintain it to constantly replace the CRD resource.

**Comment by alen-z** [comment] 2022-07-28 15:31
As one of the solution, maybe enabling the chart to add custom CRD annotations, `argocd.argoproj.io/sync-options: Replace=true` in our case, would mitigate the issue.

**Comment by monotek** [comment] 2022-07-29 07:43
duplicate of: https://github.com/prometheus-community/helm-charts/issues/1500
closed.

**Closed by monotek** 2022-07-29 07:43 UTC
Labels: bug
